name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Create dist folder
        run: mkdir dist

      - name: Copy files
        run: cp -r index.html ./css ./images ./js ./dist

      - name: Archive artifacts
        shell: bash
        run: |
          tar \  
           -czvf dist.tar.gz ${GITHUB_WORKSPACE}/dist

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ${ runner.temp }/dist.tar.gz
          retention-days: 1
          if-no-files-found: error
