name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Create dist folder
        run: mkdir "$RUNNER_TEMP/dist"

      - name: Copy files
        run: cp -r index.html ./css ./images ./js "$RUNNER_TEMP/dist"

      - name: Archive artifacts
        shell: bash
        run: |
          tar \
            --diference --hard-dereference \
            --directory "$RUNNER_TEMP/dist" \
            -cvf "$RUNNER_TEMP/dist.tar"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ${ runner.temp }/dist.tar
          retention-days: 1
          if-no-files-found: error
